### PR TITLE
Esm support

### LINKED ISSUE #11: ES Modules support
Hello! I am just starting to use your lib on commercial application I am developing and I think it rocks. 

Although I am quite aware that rarely would someone use such for the frontend, I would like to request support for ES Modules additionally to CommonJS. Publishing ESM would make the project more friendly so maybe more people could enjoy some CQRS when building corporate apps :)

I am not very versed in publishing packages to NPM but we could have a second package named `mediatr-ts/esm` as an alternative for frontend endeavors like mine.

### PR DESCRIPTION
**Pull request by brunovinicius**
Hey! I made the changes necessary to publish the lib supporting both esm and cjs. Basically followed this article 

https://thesametech.com/how-to-build-typescript-project/

I think its important to note he points out a possible problem related to simultaneously importing both versions in the same app (which is highly unlikely, but not impossible)

I must add that I never built a lib like that so I was not able to test this successfully - I used the npm pack + untar + npm link but to no avail, so at this point I am not sure if there's something wrong with what I did or there's something wrong with the way I setup the testing environment. I would appreciate if you were able to test it out on your side and tell me if it worked ok. Otherwise I will gladly keep working on this.

Tks in advance.

fixes #11

### CODE REVIEW

**Comment by m4ss1m0g** [comment]
To test the npm package, you can follow this [guide](https://dev.to/scooperdev/use-npm-pack-to-test-your-packages-locally-486e).

I didn't know that `npm build` could produce ESM and CommonJS on the same build, but I'm scared about the sentence in the article you linked: `When an application is using a package that provides both CommonJS and ES module sources, there is a risk of certain bugs if both versions of the package get loaded`.

Maybe is better that you fork the repo and build your own npm package as you suggest on issue #11 

@ffMathy maybe you have more experience with this problem? What do you suggest?

**Comment by ffMathy** [comment]
Yeah that does indeed sound scary. But the world is moving towards esm (including NPM themselves), so staying behind is probably not the better option 🙁

**Comment by brunovinicius** [comment]
I would agree that if we have to pick one, than we should go with ESM. This is certainly smt that would hinder adoption as time moves forward.

**Comment by ffMathy** [comment]
Also, I think it's only an issue if we have a bug in the code that loads both. I think that should be fairly easy to avoid. And can be tested too.

**Comment by m4ss1m0g** [comment]
@brunovinicius can you update the CHANGELOG with the support for ESM and the package version to 1.1.0? 
Then run the `npm run test:badges` to update the badge on README.
@ffMathy Thanks for your support! 
I think to remove the support on commonjs on the next major release, what do you think?

**Comment by brunovinicius** [comment]
Sure thing. I need to make sure this works properly first though. I will be able to put some more hours on it later today.

**Comment by brunovinicius** [comment]
@m4ss1m0g done. Managed to fix the problem and now it seems to be working as expected. On my application, Angular Compiler stoped complaining about CommonJS dependency. And the final bundle size dropped a bit too.

See if the CHANGELOG message feels right for you. The badges were not updated as everything is passing same as before.

**Comment by m4ss1m0g** [comment]
@brunovinicius Seems good, please update from `"version": "1.0.0"` to `"version": "1.1.0"` inside the `package.json` and run again the `npm run test:badges` to update the badge to 1.1.0

**Comment by brunovinicius** [comment]
Done. For any reason the output param for jest-coverage-badges does not work on my side so I had to copy the files manually. Might be a problem related to M1 Macs, or something. The project is being maintained by a new person in another repo.

I took the liberty to update it too. Hopefully it doesn't break on your side.

**Pull request merged**
