### PR TITLE
Rewrote docs, added behaviors and more

### PR DESCRIPTION
**Pull request by ffMathy**
I want to use this package in my work (I work for a corporation). However, for that to happen, I think these things that I propose here should be fixed. Alternatively I think I will make a fork at some point.

It's a big one. I hope it's okay, and that you can find the time for looking into it 🙏 

# Documentation
- Added new pipeline behavior example.
- Added new example of reordering execution order for both notifications and pipeline behaviors.
- Separated the documentation into "Core concepts", and then extracted the Dependency Injection part out as a separate section.

# Notification handlers
- Removed the order in the decorator. This is generally bad practise, because it breaks encapsulation. If one class knows about the order of the other classes implicitly, it is typically a smell. We can't remove the need for this entirely, but we can centralize it in one place so it's easier to see what the order of handlers are (see the new documentation on changing the order). That way, it is way less likely to implicitly break, and easier to keep track of. It also follows closer with Mediatr's own setup.
- Got rid of the `DispatcherInstance` class. Instead, we now have mapping classes (similar, but not entirely identical). See the rest of the notes.
- The `Dispatcher` has a property called `notifications` from where the notifications mappings are controlled (and execution order).
- Added new types called `INotificationClass` and `INotificationHandlerClass`. These are used for *classes* instead of *instances* of these types. The code wrongly had `INotification` specified in cases where the actual real type was `INotificationClass`. This also strengthens the code and makes it harder to write it wrong.
- The `publish` method on the `Mediator` now returns a `Promise<void>` instead of `Promise<void[]>`.

# Dispatcher
- The `Dispatcher` now just has two properties. `notifications` and `behaviors`, which control the handler mappings for each of them, and the order.

# Pipeline behaviors
- Added support for Pipeline behaviors.
- The `Dispatcher` has a property called `behaviors` from where the pipeline behavior mappings are controlled (and execution order).
- A new decorator has been introduced for this.
- A new `IPipelineBehavior` interface, as well as a `IPipelineBehaviorClass` type has been introduced.

# Boyscouting
- Changed imports to type imports where possible, to speed up compilation, and decrease the chance of accidental circular dependencies.
- Added `"importsNotUsedAsValues": "error"` to the `tsconfig.json` file, so that the TypeScript compiler will give an error if a regular import is used where a type import could have been used instead. Again, to decrease the chance of accidental circular dependencies.
- Added `"strict": true` to the `tsconfig.json` file, so that we now have full TypeScript strictness in the project.

# Miscellaneous
- Bumped package version to 1.0.0.

### CODE REVIEW

**Comment by ffMathy** [comment]
cc @m4ss1m0g (in case you don't get notifications for this kind of stuff).

**Comment by m4ss1m0g** [comment]
@ffMathy You have done great work!
Can you also update the CHANGELOG with these new improvements?

**Comment by m4ss1m0g** [comment]
Close the #5

**Comment by ffMathy** [comment]
Thanks for merging! However, I realized I forgot to follow the "keep a changelog" format, so I actually made an additional commit after. See #10 now.

Sorry about that!

**Comment by m4ss1m0g** [comment]
No problem. However, you must increment 1 the patch level of packages.json, 1.0.1 otherwise I can't publish the package

**Comment by ffMathy** [comment]
I think it's actually okay to not publish the package, as only CHANGELOG.md has changed, which is not actually part of the package. Do you agree?

**Comment by m4ss1m0g** [comment]
In this case, the PR remains open, otherwise, if I merge it tries to publish and returns an error.

**Comment by m4ss1m0g** [comment]
I think is better to merge.

**Comment by ffMathy** [comment]
Awesome stuff ❤️ thanks once again.

More improvements will come, but I don't know when.

For instance, I'd like to throw an exception if the settings get mutated after they've been used once.

That way, we can tell the user if they are mutating settings after load.

**Pull request merged**
